### ISSUE TITLE
container-example does not have a released version compatible with container v2

### ISSUE THREAD

**Issue by Abdull** [b13/container-example#17]
In a TYPO3 installation using b13/container 2.x, `composer require b13/container-example` currently fails, as there currently isn't a `container-example` version released which is compatible with `container` 2.x.

```
$ composer require b13/container-example
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires b13/container-example ^1.0 -> satisfiable by b13/container-example[1.0.0].
    - b13/container-example 1.0.0 requires b13/container ^1.0.0 -> found b13/container[1.0.0, ..., 1.6.1] but it conflicts with your root composer.json require (^2.0).
```

A workaround is to require the current master branch version:

```
composer require b13/container-example:dev-master
```

**Comment by achimfritz** [comment]
i have tagged the master with 2.0.0 (but note: this is just an example extension, so you can also require dev-master for examples ...)

**Comment by Abdull** [comment]
Thanks!
