### ISSUE TITLE
Content Element has no rendering definition

### ISSUE THREAD

**Issue by discotizer** [b13/container-example#18]
After installing the 2.0.0 examples with installed Container EXT on a typo3 11.5.15 system i got the following error in the frontend:

> Content Element with uid "7" and type "cw-normal" has no rendering definition

This is the error from the derivated examples but it also fails with the build-in ones. In the backend evertyhing is fine.
Of course the template files exists with the right name (case sensitive) as described in the doc.

**Comment by discotizer** [comment]
Registration in TS was missing - fixedi it, working now.

**Comment by datalinkgrafx** [comment]
Hi, I run into the same issue. What have you done?

**Comment by achimfritz** [comment]
Hi @datalinkgrafx , s. examle here: https://github.com/b13/container/#typoscript

**Comment by datalinkgrafx** [comment]
No
ERROR: Content Element with uid "879" and type "b13-2cols" has no rendering definition!
Typo3 11.5.22

**Comment by achimfritz** [comment]
how does your TypoScript look, have you included TS from EXT:fluid_styled_content?

**Comment by datalinkgrafx** [comment]
I changed 
ID\Myext\DataProcessing\FlexFormProcessor
to
B13\Myext\DataProcessing\FlexFormProcessor
in my extension. Now it works
Thanx
